### ISSUE TITLE
NoSuchMethodError: PublicKeyKeyEncryptionMethodGenerator.setUseWildcardKeyID

### ISSUE THREAD

**Issue by sushengloong** [vanitasvitae/pgpainless#403]
After upgrading org.pgpainless:pgpainless-sop from 1.5.1 to 1.5.6 in my project, I face the following error during encryption:-

```
java.lang.NoSuchMethodError: 'org.bouncycastle.openpgp.operator.PublicKeyKeyEncryptionMethodGenerator org.bouncycastle.openpgp.operator.PublicKeyKeyEncryptionMethodGenerator.setUseWildcardKeyID(boolean)'
at org.pgpainless.encryption_signing.EncryptionOptions.addRecipientKey(EncryptionOptions.java:274)
	at org.pgpainless.encryption_signing.EncryptionOptions.addAsRecipient(EncryptionOptions.java:262)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:211)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:199)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipients(EncryptionOptions.java:127)
	at org.pgpainless.sop.EncryptImpl.withCert(EncryptImpl.java:113)
	at sop.operation.Encrypt.withCert(Encrypt.java:147)
```

This looks like a regression bug to me. Please take a look. Thank you!

**Comment by vanitasvitae** [comment]
You probably didn't upgrade your Bouncy Castle dependency to 1.76 or another dependency pulls in an older BC version.

**Comment by sushengloong** [comment]
It's working for me after removing the older BC version. Thank you!
